### ISSUE TITLE
Use allow function as much as possible and move to common utils

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#110]
change this 

components/melecules/ConnectedWallet

```
function shortenAddress(str: string) {
  return `${str.substring(0, 6)}...${str.substring(str.length - 4)}`;
}
```

to allow function and this general one needs to move to common utils

**Comment by taijusanagi** [comment]
same to 

```
  const shortenAddress = (str: string) => {
    return `${str.substring(0, 6)}...${str.substring(str.length - 4)}`;
  };

```

components/organisms/NFTDetail

Let's keep code DRY.

**Comment by lodenrogue** [comment]
Do you mean consolidate both of these functions into 1 function that is used in place of these?
