### ISSUE TITLE
Investigate how we can integrate lens

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#117]
- Post created order in Lens
- Aggregate activity in Lens

**Comment by Aqrare** [comment]
https://refract.withlens.app/
We can add such a board in our App and the user can post Orders or check what kind of Orders are exist

**Comment by Aqrare** [comment]
https://refract.withlens.app/
In this app, users can share links and comments on the post.

Instead of this by posting Order, users will  be able to negotiate on Lens

<img width="566" alt="Screen Shot 2022-07-08 at 11 39 12" src="https://user-images.githubusercontent.com/64068653/177905944-8826b044-b300-4bd0-9ab6-16b856965983.png">

**Comment by Aqrare** [comment]
And posts or comments can be seen other SNS platform using Lens

**Comment by Aqrare** [comment]
I'm not sure what you imagine "Aggregate activity in Lens". Would be happy for you to tell me more.

**Comment by Aqrare** [comment]
This type of integration conflicts with XMTP I think. Can't both coexist somehow?

**Comment by taijusanagi** [comment]
Hey, nice thought on this.

for this
https://github.com/kaguraswap/monorepo/issues/117#issuecomment-1178483317

this is like SNS share, so we can add normal share button (like twitter), and also has lens and XMTP.

**Comment by taijusanagi** [comment]
>I'm not sure what you imagine "Aggregate activity in Lens". Would be happy for you to tell me more.

My previous understanding is wrong. No need to discuss this for lens.

I thought lens is kind of on-chain activity aggregator.

However I read this
https://cryptoslate.com/lens-protocol-a-composable-decentralized-social-graph-for-a-web3-ready-community/#:~:text=Lens%20Protocol%20is%20a%20social,to%20create%20metaverse%2Dready%20profiles.

And now I'm thinking lens is web3 SNS platform protocol which has posting function and profile.

**Comment by taijusanagi** [comment]
And I read current thought, and it is ok for the investigation now.

Let's close this issue.

I created #161
