### ISSUE TITLE
Update Inception Deck of Kagura Swap

### ISSUE THREAD

**Issue by Aqrare** [kaguraswap/monorepo#118]
- order aggregater
- remove middle man
- nfthashi integration

**Comment by taijusanagi** [comment]
Hey, this inception deck improvement should come after
https://github.com/kaguraswap/monorepo/issues/188

We can think about value of this service by comparing with 
- sudoswap
- tofuNFT

so this is very important part.

**Comment by taijusanagi** [comment]
Hey also this inception deck part should come after

https://github.com/kaguraswap/monorepo/issues/185

I think this tip model is core part of our service, so should check this first.

**Comment by taijusanagi** [comment]
Let's work here
https://github.com/kaguraswap/monorepo/wiki/Inception-Deck

**Comment by taijusanagi** [comment]
@Kentaroyamamura @ksuhara @Aqrare 
I think the current inception deck is nice for now, no value is changed for me.

**Comment by taijusanagi** [comment]
If no one point out the improve point or question, I'll close this by 15pm JST today

**Comment by Aqrare** [comment]
I also think there is no big change for the inception deck.
However, it is important to review it and have a same recognition.

Do not need to take a lot of time for this but a quick chat (~5min) produces a big value I think.
Since it seems there is no good time for all, I'd like to do a quick at the morning meeting tomorrow.

**Comment by taijusanagi** [comment]
nice suggestion! Let's do that tomorrow.

I think I develop the product along with the inception deck, and everyone can review the inception deck and product at the same time.

**Comment by taijusanagi** [comment]
Let’s close this and review tomorrow.
