### ISSUE TITLE
Wallet improvement

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#146]
https://github.com/kaguraswap/monorepo/discussions/142#discussioncomment-3105512

https://github.com/kaguraswap/monorepo/discussions/142#discussioncomment-3105567

https://github.com/kaguraswap/monorepo/discussions/142#discussioncomment-3105583

https://github.com/kaguraswap/monorepo/discussions/142#discussioncomment-3105663

**Comment by taijusanagi** [comment]
I simplified the wallet, and some styling is remainning.

**Comment by taijusanagi** [comment]
- style (include icon)
- wallet connect
- switch network and wallet (if required)

**Comment by ksuhara** [comment]
https://miro.com/app/board/uXjVOoCNSfQ=/?moveToWidget=3458764529863189408&cot=14
