### ISSUE TITLE
Improve fee modal

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#152]
https://github.com/kaguraswap/monorepo/discussions/142#discussioncomment-3105547

https://github.com/kaguraswap/monorepo/discussions/142#discussioncomment-3105552

**Comment by taijusanagi** [comment]
https://github.com/kaguraswap/monorepo/discussions/142#discussioncomment-3105601

**Comment by taijusanagi** [comment]
reference
https://github.com/kaguraswap/monorepo/discussions/193

**Comment by Aqrare** [comment]
I think it is not good to set default prices because it leads misorders.
<img width="519" alt="Screen Shot 2022-07-12 at 15 39 05" src="https://user-images.githubusercontent.com/64068653/178424964-e9034ed5-9a2a-4832-89aa-ccee3068535e.png">

**Comment by Aqrare** [comment]
https://github.com/orgs/kaguraswap/discussions/142#discussioncomment-3105601
This is already done
