### ISSUE TITLE
Implement social media sharing

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#161]
Implementing share for twitter, XMTP, lens.
#117

dividing into subtask is ok.

**Comment by taijusanagi** [comment]
UI is like this.

![Image](https://user-images.githubusercontent.com/38043569/178442858-0ece464b-d976-4c35-9f8a-2ec3d2b12f9f.png)

**Comment by Aqrare** [comment]
We can integrate
- XMTP
  - When offers are created
- Lens
  - When orders are created
- EPNS
  - When offers are created
  - NFT you want is listed
  - Receive Referral Fee
  - Your offer/order is matched
- Twitter
  - When orders are created

**Comment by taijusanagi** [comment]
@Aqrare 
Hey, I think if you integrate all of them, the task is would be too big.

So, you can just implement Twitter first for this issue, then create each issue to XMPT, Lens, EPNS

**Comment by Aqrare** [comment]
Yes, I'm just dividing and making them!

**Comment by Aqrare** [comment]
I divided this issue
XMTP #130 
Twitter #197 
Lens #l199
EPNS #128

**Comment by Aqrare** [comment]
So I'll close this issue

**Comment by taijusanagi** [comment]
ok!

**Comment by taijusanagi** [comment]
I recommend doing https://github.com/kaguraswap/monorepo/issues/197 this first.

**Comment by Aqrare** [comment]
ok! I'll do that
