### ISSUE TITLE
Invesigate Seaport tip function

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#185]
## Overview

https://indianexpress.com/article/technology/crypto/opensea-launches-seaport-heres-how-you-can-exchange-your-nft-7931579/#:~:text=In%20addition%2C%20Seaport%20users%20can,that%20of%20the%20original%20offer.

it says Seaport has tipping

## Action
Check how this is used in Seaport

(max 30m)

**Comment by taijusanagi** [comment]
@Aqrare 
hey can you take this issue??

**Comment by taijusanagi** [comment]
I commented here too
https://github.com/kaguraswap/monorepo/issues/118

This has large impact on our service, so I want to close it sooner.

**Comment by Aqrare** [comment]
Yes! 
The output is How the tip function is worked in Seaport Contract right?

**Comment by taijusanagi** [comment]
That's right! Clever!

I know seaport has fees parameter, and this fee is created when maker (in seaport term, offerer) create order and sign it.

I want to check Seaport tip is just this fee or is there any other concept we are missing.

**Comment by taijusanagi** [comment]
Hey, I found a tip here!

https://github.com/ProjectOpenSea/seaport/blob/a9552b9c89bbeeee49392ab4947d4ed93c565fbc/test/basic.spec.ts#L226

seems like fulfiller add consideration for the order.

**Comment by Aqrare** [comment]
Thank you !!!
It seems that tips in Seaport are not tips for protocol,  but tips for the order maker or order fulfiller

**Comment by taijusanagi** [comment]
Yes, we can use this! Nice function!

**Comment by taijusanagi** [comment]
I just quickly check 0x is supporting this or not.

**Comment by taijusanagi** [comment]
For this issue, I think we can close now, so please confirm and close.
