### ISSUE TITLE
implement Filter UI

### ISSUE THREAD

**Issue by ksuhara** [kaguraswap/monorepo#187]
**Is your feature request related to a problem? Please describe.**

reference 
https://pro.chakra-ui.com/components/e-commerce/product-filters

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by taijusanagi** [comment]
nice!

**Comment by taijusanagi** [comment]
Talked with ksuhara on this.
https://github.com/kaguraswap/monorepo/issues/97#issuecomment-1181209096

Let's do quick development for filter UI (no need to spend time on a design before top overall UI finalized)
