### ISSUE TITLE
Implement Sort and filter with Hasura

### ISSUE THREAD

**Issue by ksuhara** [kaguraswap/monorepo#191]
## Overview
- sort option UI
- control the firestore sort  query at the top page

**Comment by taijusanagi** [comment]
Since we moved from firebase to hasura, modified issue title.

**Comment by taijusanagi** [comment]
change where part from query to page.

```
  const { data } = useAssetSubscription({
    variables: {
      condition: { chainId: { _eq: chainId }, contractAddress: { _eq: contractAddress }, tokenId: { _eq: tokenId } },
    },
  });

```

**Comment by taijusanagi** [comment]
![Image](https://user-images.githubusercontent.com/38043569/179941574-8bc00601-2311-4b87-bca6-9fa82a7a114c.png)


https://github.com/chakra-ui/chakra-ui/issues/2925
