### ISSUE TITLE
Fix UI bug at NFT display

### ISSUE THREAD

**Issue by Aqrare** [kaguraswap/monorepo#196]
## Overview
If the description is long, the image will be streched
 
<img width="1440" alt="Screen Shot 2022-07-12 at 17 34 13" src="https://user-images.githubusercontent.com/64068653/178447199-ae2f50cf-a194-431e-a4f0-a5c52773fee4.png">

## Action
Fix

**Comment by taijusanagi** [comment]
I think we can just changing to not showing description.
