### ISSUE TITLE
[Break change] Improve user order create process

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#204]
Implementing this

<img width="711" alt="Screen Shot 2022-07-13 at 0 04 47" src="https://user-images.githubusercontent.com/38043569/178522499-fdb28f79-ff27-4e62-b4f6-77e34cbdd78c.png">

**Comment by ksuhara** [comment]
I agree! 
maybe no need for mypage if we have filter for that in top page order list.

**Comment by taijusanagi** [comment]
Thanks!

discussion here too.
https://github.com/orgs/kaguraswap/discussions/200#discussion-4210295
