### ISSUE TITLE
Modify network config to support chains

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#207]
## Overview
The previously supported chain is selected by protocol and API.
But we decided not to use API so we can support all chains which the protocol supports.

## Action
Update network config to support chain.

## Reference
https://github.com/kaguraswap/monorepo/issues/7

**Comment by ksuhara** [comment]
seaport
https://github.com/ProjectOpenSea/seaport#deployments

0x v4
https://docs.0x.org/developer-resources/contract-addresses#0x-v4
