### ISSUE TITLE
Investigate SwapStreet - A P2P multi-asset swap protocol

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#211]
This look very similar to our service
https://www.swapstreet.io/

output
- monetize
- screenshot 
- analytic of trade volume

**Comment by taijusanagi** [comment]
Screenshot

![Image](https://user-images.githubusercontent.com/38043569/178888396-2cbe80a1-0b87-4204-93cc-865ecb82b77c.png)

![Image](https://user-images.githubusercontent.com/38043569/178888403-4dd82b67-2f99-4bd3-b2f7-68a5ea7ad656.png)

**Comment by taijusanagi** [comment]
Supported multichain

**Comment by ksuhara** [comment]
monetize
- take $30 each for transactions.

![Image](https://user-images.githubusercontent.com/45842611/178906535-053fd8e8-812a-4548-bb9b-09319d5518dd.png)

**Comment by ksuhara** [comment]
only 19 offers are filled 

check here and filter with "filled orders"
https://app.swapstreet.io/swap

not a very active project anymore
