### ISSUE TITLE
Investigate Atomic0 - A community-drive Ethereum NFT marketplace

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#212]
[Atomic0](https://atomic0.com/) - A community-drive Ethereum NFT marketplace

output

monetize
screenshot
analytic of trade volume

**Comment by taijusanagi** [comment]
Focus on fee free

![Image](https://user-images.githubusercontent.com/38043569/178888584-892f69b6-08c6-42e0-b290-32a75f2b1411.png)

**Comment by taijusanagi** [comment]
Mainnet is supported now.

**Comment by ksuhara** [comment]
monetization
- no plan for near tearm
- focused on delivering the best tools for traders and actively raising a seed round to fund 
- long term, secret.

![Image](https://user-images.githubusercontent.com/45842611/178913618-dd394030-d2a2-4e68-9bd5-ea76bb33c078.png)

**Comment by taijusanagi** [comment]
This is a bit inactive issue, and we know this service well, so let's close.
