### ISSUE TITLE
Understand the limitation of seaport protocol and workarounds

### ISSUE THREAD

**Issue by ksuhara** [kaguraswap/monorepo#213]

**Comment by ksuhara** [comment]
https://zenn.dev/suhara_ponta/scraps/c83ea607c29320

**Comment by taijusanagi** [comment]
https://github.com/kaguraswap/monorepo/issues/157#issuecomment-1190956347

**Comment by taijusanagi** [comment]
Hey this is bit general issue, and I want the specific issue to implement and investigate.

I see you have the page to investigate, let's close this issue.
