### ISSUE TITLE
All process refinement and UI refinement

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#234]
- check current development
- refine user story / customer journey

**Comment by taijusanagi** [comment]
customer journey
- journey integrate service
  - integrating chocomint
  - integrating 3rd party website

**Comment by ksuhara** [comment]
doing walkthrough of current development.
- better to have feature for bulk NFT importing (ex. input contractAddress and then all nfts will be registerd)
- better to have reaction (loading UI) of NFT importing

**Comment by ksuhara** [comment]
bug?
- after buying NFT, nft page shows Cancel button

**Comment by ksuhara** [comment]
- Maybe better to have a preview feature of the image (expand the image and remove information tags). Imaging embedding NFT page iframe to the mintpage

**Comment by taijusanagi** [comment]
lgtm
