### ISSUE TITLE
Improve Asset page design

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#241]

**Comment by ksuhara** [comment]
- want to know how much tip will go to whom before fulfilling
- Imaging embedding NFT page iframe to the mint page
  - better to have all buttons inside the image
  - It may be better to have a preview feature of the image (expand the image and remove information tags).

**Comment by ksuhara** [comment]
some reference
https://miro.com/app/board/uXjVOoCNSfQ=/?moveToWidget=3458764529711086998&cot=14

**Comment by taijusanagi** [comment]
implement this

![Screen Shot 2022-07-21 at 11 12 02](https://user-images.githubusercontent.com/38043569/180114832-31d416c4-2fb0-44a2-b558-affcaf4e0bc2.png)
