### ISSUE TITLE
Implement loading in assets

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#250]
I want this 
https://hasura.io/blog/vue-tutorial-implement-infinite-scroll-vue-apollo-hasura-graphql/

**Comment by ksuhara** [comment]
this could also help
https://sysgears.com/articles/how-to-implement-infinite-scroll-with-graphql-and-react/

**Comment by taijusanagi** [comment]
maybe you can use isReverse for the previous data fetching.

https://www.npmjs.com/package/react-infinite-scroller

**Comment by taijusanagi** [comment]
this seems useful to manage browser back
https://blog.ojisan.io/i-hate-infinite-scroll/#%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%83%90%E3%83%83%E3%82%AF%E3%81%99%E3%82%8B%E3%81%A8%E3%81%BE%E3%81%9F-1-%E3%81%8B%E3%82%89%E3%82%B9%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%AB%E3%82%92%E3%81%97%E7%9B%B4%E3%81%99%E3%81%93%E3%81%A8%E3%81%AB%E3%81%AA%E3%82%8B

**Comment by taijusanagi** [comment]
has more implementation
https://zenn.dev/syu/articles/1aeebcf13172d1#%E7%84%A1%E9%99%90%E3%82%B9%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%AB%E5%87%A6%E7%90%86

**Comment by taijusanagi** [comment]
maybe you can use fetch more and it may store previous record
https://www.apollographql.com/docs/react/pagination/core-api/#the-fetchmore-function

**Comment by taijusanagi** [comment]
@ksuhara 
For performance, can you please check if possible to integrate with

react-virtual
https://tanstack.com/virtual/v3/docs/guide/introduction

maybe 10-20m research is enough.
