### ISSUE TITLE
Event trigger for Hasura cleaning

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#252]
Add event trigger to call cleaning
https://hasura.io/docs/latest/graphql/core/event-triggers/index/

**Comment by taijusanagi** [comment]
@ksuhara 
Hey can you please add this to Hasura? 

Open the Hasura console and add the event trigger.
This should affect the metadata file.

Consideration
- how to change url for local and prod
   - I think You can pass the env value, but this part you can try to put hardcode localhost to check first

**Comment by ksuhara** [comment]
@taijusanagi 
I added cron trigger with this [pr]( https://github.com/kaguraswap/monorepo/pull/246/files)  but does it need to be an event trigger?

I didn't check cron trigger working,  so will check and  consider the local / prod switch

**Comment by taijusanagi** [comment]
Oh, sorry I did not check that is already implemented.

>local / prod switch 
This part I can take care of by 
https://github.com/kaguraswap/monorepo/issues/233

so let's close this.

**Comment by ksuhara** [comment]
thanks!
