### ISSUE TITLE
Improve Loading

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#262]
## Overview
- currently loading is only showing same data
- loading text needs better view

**Comment by taijusanagi** [comment]
@ksuhara 
Can you please check if this is diplayed in story book too??

**Comment by ksuhara** [comment]
wanted to use https://github.com/davidhu2000/react-spinners but couldn't import because it `has unmet peer dependency "react-dom@^16.0.0 || ^17.0.0 || ^18.0.0".`

will use https://mhnpd.github.io/react-loader-spinner/three-dots
