### ISSUE TITLE
Investigate Seaport criteria order functions

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#32]
Seaport has criteria for the order, let's check what it is.

**Comment by Aqrare** [comment]
Each item on a listing can also optionally specify that some “criteria” be met in place of requiring a specific tokenId, enabling collection-level and trait-level offers

**Comment by Aqrare** [comment]
It is interesting!!  Next, I'll research how to use this

**Comment by Aqrare** [comment]
<img width="454" alt="Screen Shot 2022-07-07 at 15 26 35" src="https://user-images.githubusercontent.com/64068653/177706110-06be0754-5388-47a4-ad3e-2054be8c0a99.png">

The test case use token IDs for the criteria..........?
How to fetch from traits or level?

**Comment by Aqrare** [comment]
I'm not sure what is the different between set identifier in offer and in Criteria.......

**Comment by taijusanagi** [comment]
Hey if you are facing a difficult topic and think need a certain time to investigate, you can always ask the team for help.

**Comment by taijusanagi** [comment]
I checked and found good test case.

https://github.com/ProjectOpenSea/seaport/blob/2f2fc9969f44b9ce57bc9ce4eb1e84d9a4e46b3f/test/index.js#L3894

This criteria base order is using merkle tree, so...

In the case user want to sell any of NFT which as certain traits..

1. get token ids for the NFT which has the trait in off-chain.
2. create root using token Ids
3 put the root in the offer

then users can make criteria-based orders.

so it is enough for the current investigation, and when you are going to implement this, we can make implement task.
