### ISSUE TITLE
Invesitgate how to use conduit

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#33]
Let's check this.

**Comment by taijusanagi** [comment]
If you do this, I prefer to know, tell how we can use it, and make implementation proposal for kaguraswap

**Comment by Aqrare** [comment]
### What is Conduit ?
```
A conduit is a contract where offerers set token approvals. The owner of the conduit can add and remove "channels" for the conduit, and registered channels can instruct the conduit on how to transfer tokens. These two concepts enable extensibility and upgradeability in a fully "opt-in" fashion, giving creators, collectors, and platforms additional ability to make their own choices regarding how they utilize Seaport while maintaining broad composability with other listings on the protocol.
```

**Comment by Aqrare** [comment]
This contract serves as an originator for "proxied" transfers. Each conduit is deployed and controlled by a "conduit controller" that can
  add and remove "channels" or contracts that can instruct the conduit to transfer approved ERC20/721/1155 tokens. IMPORTANT NOTE: each conduit has an owner that can arbitrarily add or remove channels, and a malicious or negligent owner can add a channel that allows for any approved ERC20/721/1155 tokens to be taken immediately — be extremely cautious with what conduits you give token approvals to!

**Comment by taijusanagi** [comment]
please check this too
https://github.com/kaguraswap/monorepo/issues/74

I think it is related

**Comment by taijusanagi** [comment]
I asked opensea dev and they said the conduit can be used for flexible fee distribution

**Comment by taijusanagi** [comment]
I got clearer understanding 
https://twitter.com/Tudmotu/status/1528399585391136770?s=20&t=jkPSSH0hwakT1w3X8oWvgg

use can only trust us by this conduit.
