### ISSUE TITLE
Create Seaport analysis dashboard on dune

### ISSUE THREAD

**Issue by ksuhara** [kaguraswap/monorepo#57]

**Comment by Aqrare** [comment]
https://dune.com/Marcov/opensea-seaport

We can see basic information from here!
We'll create specialized query if necessary

**Comment by Aqrare** [comment]
Want to know what token types of transactions are popular

e.g ERC721 <=> ERC721 or ERC721 <=> Native token

**Comment by taijusanagi** [comment]
Hey seaport supports many types of trade.

It is not good idea to keep this general issue.
Instead, we can create very specify issue like "query how many % is by Kaguraswap in all Seaport transaction"

So let's close this isseu.
