### ISSUE TITLE
Integrate slack with github

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#85]
I want this
https://matsu.teraren.com/blog/2021/01/19/github-mention-slack/

Also, I want notification for moving issue to in-progress

**Comment by Aqrare** [comment]
@taijusanagi @ksuhara 
This is a test!!!!!!

**Comment by Aqrare** [comment]
@Aqrare 
Helllllooooooo

**Comment by Aqrare** [comment]
@Aqrare How are you ?

**Comment by Aqrare** [comment]
@taijusanagi @ksuhara 
Slack could be integrated!!
