### ISSUE TITLE
Implement firebase auth to make security rule to allow only maker can create the order

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#86]
This is done by 

- adding function to make the challenge
- sign by the challenge
- if signed properly, sign in with Firebase auth
- if the user change wallet, the firebase auth should be refreshed too

**Comment by taijusanagi** [comment]
but we can ignore this by changing create order process in server-side.
This architecture also has benefit that we can use that as global order relayer too.

**Comment by ksuhara** [comment]
what is the downside of creating orders on server-side?  sounds good to me

**Comment by taijusanagi** [comment]
just some validate development and some performance issue but it should not be big problem

**Comment by taijusanagi** [comment]
I prefer no auth, just web3 wallet implementation
