### ISSUE TITLE
Control NFTDetail view based on status

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#94]
sell/offer/buy/canncel

**Comment by ksuhara** [comment]
- nft.holder == connected user
  - no order
    - "List for Sale" button
  - order.direction == "sell"
    - "Cancel" button
  - order.direction == "buy"
    - "Accept Offer" button
- nft.holder != connected user
  - no order || order.direction == "buy"
    - "Make Offer" button
  - order.direction == "sell"
    - "Buy now" button and "Make Offer" button

**Comment by taijusanagi** [comment]
```
nft.holder != connected user
no order || order.direction == "buy"
"Make Offer" button
order.direction == "sell"
"Buy now" button and "Make Offer" button

-> 

nft.holder != connected user
order.direction != "sell"
"Make Offer" button
order.direction == "sell"
"Buy now" button and "Make Offer" button


```

**Comment by taijusanagi** [comment]
```
nft.holder == connected user
no order
"List for Sale" button
order.direction == "sell"
"Cancel" button
order.direction == "buy"
"Accept Offer" button
```

nft may have sell-order and offer-order at the same time.

but this can be take cared by 

https://github.com/kaguraswap/monorepo/issues/105

so you can implement as you mentioned.

**Comment by taijusanagi** [comment]
@ksuhara 
I came up with new implementation patten, please discuss here first!!

https://github.com/orgs/kaguraswap/discussions/124#discussioncomment-3104684

**Comment by taijusanagi** [comment]
As discussed here, this is not required
