### ISSUE TITLE
Implement filter in toppage

### ISSUE THREAD

**Issue by taijusanagi** [kaguraswap/monorepo#97]
at least

- network

**Comment by ksuhara** [comment]
how should i filter orders? firebase query or just filter at the frontend.

thinking about how I  should pass the query from child component to parent.

**Comment by taijusanagi** [comment]
For this, I have idea to implement.

1. firebase query using query param using use router. And useEffect should depends on the query. this is in page level 

2. use the shallow route to pass the filter param to URL
https://nextjs.org/docs/routing/shallow-routing

3. When url query changed, the useEffect re-render the component.

**Comment by ksuhara** [comment]
thanks! didn't know about shallow routing

**Comment by taijusanagi** [comment]
@ksuhara 
Hey! 

So... I think you better to 

1. Make PR only for the logic part
2. Make overal top page UI 
3. implement filter view

I said you can separate the issue into the logic and view part.

This is because the view part is highly affected by this issue

https://github.com/kaguraswap/monorepo/issues/186

Because top-page create-order and filter is very important part for UX of KaguraSwap.
